Netgen\LiveVotingBundle\Entity\Answer:
    type: entity
    table: answer
    id:
        id:
            type: integer
            generator: {strategy: AUTO}
    fields:
        answer:
            type: integer

    manyToOne:
        user:
            targetEntity: Netgen\LiveVotingBundle\Entity\User
            joinColumn:
                name: user_id
                referencedColumnId: id
                odDelete: CASCADE

        question:
            targetEntity: Netgen\LiveVotingBundle\Entity\Question
            inversedBy: answers
            joinColumn:
                name: question_id
                referencedColumnId: id
                onDelete: CASCADE