Netgen\LiveVotingBundle\Entity\Question:
    type: entity
    table: question
    id:
        id:
            type: integer
            generator: {strategy: AUTO}
    fields:
        question:
            type: string
            length: 255
        votingEnabled:
            type: boolean
            default: false
        question_type:
            type: integer
    oneToMany:
        answers:
            targetEntity: Netgen\LiveVotingBundle\Entity\Answer
            mappedBy: question
    manyToOne:
        event:
            targetEntity: Netgen\LiveVotingBundle\Entity\Event
            inversedBy: questions
            joinColumn:
                name: question_id
                referencedColumnId: id
                onDelete: CASCADE
