Netgen\LiveVotingBundle\Entity\User:
    type: entity
    table: user
    id:
        id:
            type: string
            length: 128
    fields:
        email:
            type: string
            length: 128
            nullable: true
        password:
            type: string
            length: 128
            nullable: true

#    oneToMany:
#        vote:
#            targetEntity: Netgen\LiveVotingBundle\Entity\Vote
#            mappedBy: user_id

