Netgen\LiveVotingBundle\Entity\User:
    type: entity
    repositoryClass: Netgen\LiveVotingBundle\Entity\UserRepository
    table: user
    id:
        id:
            type: string
            length: 128
    fields:
        username:
            type: string
            length: 128
            nullable: true
        email:
            type: string
            length: 128
            nullable: true
        password:
            type: string
            length: 128
            nullable: true
        enabled:
            type: boolean
            default: true
        gender:
            type: string
            length: '10'
        country:
            type: string
            length: '128'
        city:
            type: string
            length: '128'
        tshirt:
            type: string
            length: '128'
        foodPreference:
            type: string
            length: '128'

    oneToMany:
        registrations:
            targetEntity: Netgen\LiveVotingBundle\Entity\Registration
            mappedBy: user

#        vote:
#            targetEntity: Netgen\LiveVotingBundle\Entity\Vote
#            mappedBy: user_id

