Netgen\LiveVotingBundle\Entity\Vote:
    type: entity
    table: vote
    id:
        id:
            type: integer
            generator: {strategy: AUTO}
    fields:
        rate:
            type: integer

    manyToOne:
        user:
            targetEntity: Netgen\LiveVotingBundle\Entity\User
            joinColumn:
                name: user_id
                referencedColumnId: id

        presentation:
            targetEntity: Netgen\LiveVotingBundle\Entity\Presentation
            inversedBy: votes
            joinColumn:
                name: presentation_id
                referencedColumnId: id
                onDelete: CASCADE

        event:
            targetEntity: Netgen\LiveVotingBundle\Entity\Event
            inversedBy: votes
            joinColumn:
                name: event_id
                referencedColumnId: id