root:
    path: /
    defaults: {_controller: LiveVotingBundle:Dashboard:index}

user_landing:
    path:    /events/
    defaults: {_controller: LiveVotingBundle:Index:landing}

user_presentations:
    path:    /user/presentations
    defaults: {_controller: LiveVotingBundle:PresentationUser:index}
    requirements:
        user_id: \d+

user_presentation_edit:
    path:    /user/presentations/{id}/edit
    defaults: { _controller: "LiveVotingBundle:PresentationUser:edit" }

user_presentation_update:
    path:    /user/presentations/{id}/update
    defaults: { _controller: "LiveVotingBundle:PresentationUser:update" }
    requirements: {_method: post|put}

user_edit:
    path:    /user/edit
    defaults: { _controller: "LiveVotingBundle:User:edit" }
    defaults: { _controller: "LiveVotingBundle:User:edit" }
    requirements: {_method: get}

user_update:
    path:    /user/edit
    defaults: { _controller: "LiveVotingBundle:User:update" }
    requirements: { _method: post|put}

user_csv_import:
    path: /admin/user/import
    defaults: {_controller: "LiveVotingBundle:UserAdmin:importCsv"}
    requirements: {_method: get}

user_csv_process_import:
    path: /admin/user/import
    defaults: {_controller: "LiveVotingBundle:UserAdmin:processImportCsv"}
    requirements: {_method: post}

user_comment_presentation:
    path: /user/comment/presentation/{presentationId}
    defaults: {_controller: "LiveVotingBundle:User:commentPresentation"}
    requirements: {_method: post}

user_comment_event:
    path: /user/comment/event/{eventId}
    defaults: {_controller: "LiveVotingBundle:User:commentEvent"}
    requirements: {_method: post}

user_upload_image_presentation:
    path: /user/uploadimage/presentation/{presentationId}
    defaults: {_controller: "LiveVotingBundle:User:uploadImagePresentation"}
    requirements: {_method: post}

csv_export:
    path:    /admin/export
    defaults: { _controller: "LiveVotingBundle:Export:generateCsv" }

event:
    path:    /events/{event_id}
    defaults: {_controller: LiveVotingBundle:Event:index, event_id: -1}
    requirements:
        event_id: -?\d+

event_status:
    path: /user/event_status/{event_id}
    defaults: {_controller: LiveVotingBundle:Event:eventStatus, event_id: -1}

vote:
    path: /user/vote/{presentation_id}
    defaults: {_controller: LiveVotingBundle:Vote:vote, presentation_id: null}
    requirements: { _method: post }

result:
    path: /events/live_results/{event_id}
    defaults: {_controller: LiveVotingBundle:Result:index}

question:
    path: /user/question/{event_id}
    defaults: {_controller: LiveVotingBundle:Event:indexAnswer, event_id: -1}
    requirements:
        event_id: \d+

answer:
    path: /user/answer/{question_id}
    defaults: {_controller: LiveVotingBundle:Answer:answer}
    requirements: { _method: post }
    requirements:
        question_id: \d+

event_status_question:
    path: /user/event_status_question/{event_id}
    defaults: {_controller: LiveVotingBundle:Event:eventStatusQuestion}

result_json:
    path: /live_results_api/{event_id}
    defaults: {_controller: LiveVotingBundle:Result:getResults}

table_results:
    path: /table_results/{event_id}
    defaults: {_controller: LiveVotingBundle:Result:getTable}


# ADMIN ROUTING #
admin_index:
    path:     /admin/
    defaults: { _controller: "LiveVotingBundle:Admin:index" }

LiveVotingBundle_admin_event:
    resource: "@LiveVotingBundle/Resources/config/routing/event.yml"
    prefix:   /admin/event

LiveVotingBundle_admin_presentation:
    resource: "@LiveVotingBundle/Resources/config/routing/presentation.yml"
    prefix:   /admin/presentation

LiveVotingBundle_admin_result:
    resource: "@LiveVotingBundle/Resources/config/routing/result.yml"
    prefix: /admin/result

LiveVotingBundle_admin_prize_draw:
    resource: "@LiveVotingBundle/Resources/config/routing/prizeDraw.yml"
    prefix: /admin/prize_draw

LiveVotingBundle_admin_question:
    resource: "@LiveVotingBundle/Resources/config/routing/question.yml"
    prefix: /admin/question

LiveVotingBundle_admin_registration:
    resource: "@LiveVotingBundle/Resources/config/routing/registration.yml"
    prefix: /admin/registration

#New page for user manipulation#
LiveVotingBundle_admin_user:
    resource: "@LiveVotingBundle/Resources/config/routing/user.yml"
    prefix: /admin/user

admin_presentation_publish:
    path: /admin/events/{event_id}/presentations/publish
    defaults: { _controller: LiveVotingBundle:PresentationAdmin:publish, event_id: -1}
    requirements:
        event_id: \d+
    methods:  [POST, GET]


#User presentations
#LiveVotingBundle_user_presentations:
#    path: /user/presentations
#    defaults: {_controller: LiveVotingBundle:PresentationUser:index}

#USER LOGIN ROUTING#
user_login:
    path:    /login/{activateHash}/{typeOf}
    defaults: { _controller: LiveVotingBundle:Security:userLogin, activateHash: null, typeOf: null }

user_login_check:
    path:    /login_check

user_logout:
    path:    /logout

user_checkemail:
    path: /checkemail
    defaults: {_controller: LiveVotingBundle:Security:checkEmail}

#ADMIN LOGIN ROUTING#
admin_login:
    path:    /admin/login
    defaults: { _controller: LiveVotingBundle:Security:adminLogin }

admin_login_check:
    path:    /admin/login_check

admin_logout:
    path:    /admin/logout

# Dashboard #

dashboard_presentations:
  path: /dashboard/presentations
  defaults: {_controller: LiveVotingBundle:Dashboard:getPresentations}

dashboard_live_schedule:
  path: /dashboard/liveschedule
  defaults: {_controller: LiveVotingBundle:Dashboard:getLiveSchedule}

#EMAIL LOGIN#
email_login:
    path: /login/

send_email_login:
    path: /admin/user/send_email_login/{typeOf}/{eventId}
    defaults: {_controller: LiveVotingBundle:UserAdmin:loginEmail, typeOf: null}

send_one_email_login:
    path: /admin/user/send_one_email_login/{typeOf}/{id}
    defaults: {_controller: LiveVotingBundle:UserAdmin:oneUserLoginEmail, id: null, typeOf: null }

latest_comments:
    path: /comments/{number}
    defaults: { _controller: LiveVotingBundle:Comments:getComment, number: 5}