live_voting_homepage:
    path:     /hello/{name}
    defaults: { _controller: LiveVotingBundle:Default:index }

presentations:
    path:   /presentations
    defaults: {_controller: LiveVotingBundle:Presentation:presentations}

status:
    path:   /status
    defaults: {_controller: LiveVotingBundle:Brain:status}

index:
    path:    /
    defaults: {_controller: LiveVotingBundle:Index:index}

index2:
    path:    /index2/{event_id}
    defaults: {_controller: LiveVotingBundle:Index:index2, event_id: -1}
    requirements:
        event_id: -?\d+
        #negative numbers

event_status:
    path: /event_status/{event_id}
    defaults: {_controller: LiveVotingBundle:Event:eventStatus, event_id: -1}

vote:
    path: /vote/{presentation_id}
    defaults: {_controller: LiveVotingBundle:Vote:vote, presentation_id: -1}


# ADMIN ROUTING #
LiveVotingBundle_admin_event:
    resource: "@LiveVotingBundle/Resources/config/routing/event.yml"
    prefix:   /admin/event


LiveVotingBundle_admin_presentation:
    resource: "@LiveVotingBundle/Resources/config/routing/presentation.yml"
    prefix:   /admin/presentation