root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /user/
        permanent: true

user_landing:
    path:    /user/
    defaults: {_controller: LiveVotingBundle:Index:landig}


event:
    path:    /event/{event_id}
    defaults: {_controller: LiveVotingBundle:Event:index, event_id: -1}
    requirements:
        event_id: -?\d+
        #negative numbers

event_status:
    path: /event_status/{event_id}
    defaults: {_controller: LiveVotingBundle:Event:eventStatus, event_id: -1}

vote:
    path: /vote/{presentation_id}
    defaults: {_controller: LiveVotingBundle:Vote:vote, presentation_id: -1}
    requirements: { _method: post }

result:
    path: /live_results/{event_id}
    defaults: {_controller: LiveVotingBundle:Result:index}

result_json:
    path: /live_results_api/{event_id}
    defaults: {_controller: LiveVotingBundle:Result:getResults}

table_results:
    path: /table_results/{event_id}
    defaults: {_controller: LiveVotingBundle:Result:getTable}


# ADMIN ROUTING #
admin_index:
    path:     /admin/
    defaults: { _controller: "LiveVotingBundle:EventAdmin:index" }

LiveVotingBundle_admin_event:
    resource: "@LiveVotingBundle/Resources/config/routing/event.yml"
    prefix:   /admin/event

LiveVotingBundle_admin_presentation:
    resource: "@LiveVotingBundle/Resources/config/routing/presentation.yml"
    prefix:   /admin/presentation

LiveVotingBundle_admin_result:
    resource: "@LiveVotingBundle/Resources/config/routing/result.yml"
    prefix: /admin/result

#New page for user manipulation#
LiveVotingBundle_admin_user:
    resource: "@LiveVotingBundle/Resources/config/routing/user.yml"
    prefix: /admin/user

#USER LOGIN ROUTING#


user_login:
    path:    /user/login
    defaults: { _controller: LiveVotingBundle:UserSecurity:login }

user_login_check:
    path:    /user/login_check

admin_login:
    path:   /admin/login
    defaults: {_controller : LiveVotingBundle:Security:login}

admin_login_check:
   path: /admin/login_check

logout:
    path:    user/logout

admin_logout:
    path:    /admin/logout