parameters:
    live_voting.result.class: Netgen\LiveVotingBundle\Features\Result\Result

services:
#    live_voting.example:
#        class: %live_voting.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    live_voting.result:
          class: %live_voting.result.class%
          arguments: [event_id]