parameters:
    live_voting.result.class: Netgen\LiveVotingBundle\Features\Result\Result
    live_voting.handlerequest.class: Netgen\LiveVotingBundle\Features\Request\ValidateRequest

services:
#    live_voting.example:
#        class: %live_voting.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    live_voting.result:
          class: %live_voting.result.class%
          arguments: [@doctrine.orm.entity_manager, event_id]
    live_voting.handlerequest:
          class: %live_voting.handlerequest.class%
          arguments: [@request_stack, @doctrine.orm.entity_manager, event_id]