security:
    providers:
        in_memory:
            memory:
                users:
                    admin: { password: morskipas, roles: 'ROLE_ADMIN' }

    access_control:
        - { path: ^/admin/, roles: ROLE_ADMIN }
        - { path: ^/admin, roles: ROLE_ADMIN }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        secured_area:
            pattern: ^/
            anonymous: ~
            http_basic:
                realm: "LiveVoting admin panel"

        default:
            anonymous: ~
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
