admin_presentation:
    path:     /event_id/{event_id}
    defaults: { _controller: "LiveVotingBundle:PresentationAdmin:index" }


admin_presentation_new:
    path:     /new
    defaults: { _controller: "LiveVotingBundle:PresentationAdmin:new" }

admin_presentation_create:
    path:     /create
    defaults: { _controller: "LiveVotingBundle:PresentationAdmin:create" }
    requirements: { _method: post }

admin_presentation_edit:
    path:     /{id}/edit
    defaults: { _controller: "LiveVotingBundle:PresentationAdmin:edit" }

admin_presentation_update:
    path:     /{id}/update
    defaults: { _controller: "LiveVotingBundle:PresentationAdmin:update" }
    requirements: { _method: post|put }