admin_question:
    path:     /event_id/{event_id}
    defaults: { _controller: "LiveVotingBundle:QuestionAdmin:index" }

admin_question_show:
    path:     /{id}/show
    defaults: { _controller: "LiveVotingBundle:QuestionAdmin:show" }

admin_question_new:
    path:     /{event_id}/new
    defaults: { _controller: "LiveVotingBundle:QuestionAdmin:new" }

admin_question_create:
    path:     /{event_id}/create
    defaults: { _controller: "LiveVotingBundle:QuestionAdmin:create" }
    requirements: { _method: post }

admin_question_edit:
    path:     /{id}/edit
    defaults: { _controller: "LiveVotingBundle:QuestionAdmin:edit" }

admin_question_view_answers:
    path:     /{id}/answers
    defaults: { _controller: "LiveVotingBundle:QuestionAdmin:viewAnswers" }

admin_question_update:
    path:     /{id}/update
    defaults: { _controller: "LiveVotingBundle:QuestionAdmin:update" }
    requirements: { _method: post|put }

admin_question_vote_enable:
    path:     /{id}/voting_status
    defaults: { _controller: "LiveVotingBundle:QuestionAdmin:enableDisable" }
    requirements: { _method: put }

admin_question_delete:
    path:     /{id}/delete
    defaults: { _controller: "LiveVotingBundle:QuestionAdmin:delete" }

admin_question_results:
    path:     /event_id/{event_id}/results
    defaults: { _controller: "LiveVotingBundle:QuestionAdmin:viewResults" }

admin_result_questions_json:
    path: /live_results_questions_api/{event_id}
    defaults: {_controller: LiveVotingBundle:QuestionAdmin:getResults}